# Site settings
title: Save Riverside Bridge
email: saveriversidebridge@gmail.com
description: "The Save the Riverside Initiative is an effort to preserve the Riverside Bridge in Ozark, Missouri"
baseurl: ""
url: "http://saveriversidebridge.com"
twitter_username: jekyllrb
github_username:  zachdyer

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
