# Site settings
title: Save Riverside Bridge
email: saveriversidebridge@gmail.com
description: "The Save the Riverside Initiative is an effort to preserve the Riverside Bridge in Ozark, Missouri"
url: "http://saveriversidebridge.com"

# Build settings
markdown: kramdown
